# Generated by Django 3.0.4 on 2020-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayya', '0002_auto_20200316_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bitcoin_add_or_bank_acct',
            field=models.CharField(max_length=255, verbose_name='bitcoin address or bank account no'),
        ),
    ]
